### PR TITLE
bump editor and update plugin configs

### PR DESCRIPTION
**Pull request by abeforgit**
## Overview

bumps editor and plugins to latest, updates the config and enables the template comments plugin.
I've left out the snippet plugin for now as it's not entirely clear how vendors will interact with that one.
also updated readme, but did it quickly, so a review is appreciated
##### connected issues and PRs:

[GN-4482](https://binnenland.atlassian.net/browse/GN-4482)

### Setup

`npm link` the above PR of the plugins, and ember serve

### How to test/reproduce

check plugins work as intended
### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] changelog
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Review by x-m-el — CHANGES_REQUESTED** [review]
```
<RdfaDatePlugin::Card
              @controller={{this.controller}}
              @options={{this.config.date}}
            />
```
Is missing (can't edit a date variable). You deleted it but probably forgot to add it back when refactoring :)

There are three `SimpleEditorComponent.js` files but I can't figure out what they're for. Mistake push or are they actually needed?

Some other bugs that are not related to this PR (e.g. missing config for `articleStructure`).

There is now both `controller.initialize` and `controller.setHtmlContent`. `initialize` will also create a new doc node (currently only document language can change because of this), however, using `initialize` looses the doc history. `setHtmlContent` will not parse a new doc node (new language not parsed), but will keep history.
I think for embeddable users, keeping history intact is more important, so using `setHtmlContent` is better. Or we should expose both ways and explain the difference. But that's not trivial, as this has to include an explanation of document language and how to set it, too.
=> For this PR I'd leave using setHtmlContent, as it feels the most logical for an end user.

Besides that changes and upgrade seem to work well :+1:

**Comment by abeforgit** [comment]
> There are three `SimpleEditorComponent.js` files but I can't figure out what they're for. Mistake push or are they actually needed?

how the hell did those get there xD

**Review by x-m-el — APPROVED** [review]

**Review by elpoelma — CHANGES_REQUESTED** [review]
Seems to work nicely overall, just noticed some things:

- Users are unable to insert a location variable
- Users can insert addresses in two ways: using the variable insert dropdown and the address insert button.

**Comment by abeforgit** [comment]
thought I could be cool and get rid of ED, but turns out plugins still technically need it.
led me down an insane rabbithole about peerdeps, more on that in the plugin repo

**Comment by x-m-el** [comment]
@elpoelma I cleaned up the removal of template-variable and fixed both issues you mentioned.

Could you re-review? I think this can be merged then.

Obviously readme isn't perfect (but that will be reworked anyway).

**Review by elpoelma — APPROVED** [review]

**Pull request merged**
