### PR TITLE
GN-4526: use language based on user browser's locale and add locale helpers

### PR DESCRIPTION
**Pull request by x-m-el**
## Overview
- The localization did not work, everything always displayed in English. This is fixed.
- Consumers might not care about localization and just want to have every user see the same (probably Dutch :) ) UI. For this, some functions were added.

##### connected issues and PRs:
- fixes https://binnenland.atlassian.net/browse/GN-4526

### How to test/reproduce
- see that changing browser language switches up the language of UI.
- see that using `setLocalTo...` after initEditor changes the language, no matter what your browser locale is.
- see that running `setLocalTo...` inside the browser's console switches up the language (see under "developer" "How it works" in the readme for how to do this).

### Challenges/uncertainties
- I kept the API for changing local simple to avoid keeping it complicated. It gives all the tools to create a locale switch button or to make sure the local follows that of the main app that uses the editor.
- I removed "The display format of these dates can be configured in the localization initializer.", because I had no idea what this actually meant. As far as I can see, it just follows the local as used by other plugins.
- some things aren't translated correctly yet, like the dropdown of the variables. Depending on when this gets reviewed I'll fix that here or in another PR :shrug:

### CODE REVIEW

**Review by elpoelma — CHANGES_REQUESTED** [review]
I like that there are simple functions which allow for setting the editor in dutch/english.

I would also add a more generic method `setLocale` which accepts any language/locale string (with a fallback to `nl-BE`).

**Comment by elpoelma** [comment]
Additionally: could you also add a changeset?

**Comment by x-m-el** [comment]
Wans't sure about a general setLocale, because we only support two of them.
However, no sense in not providing it and giving this info in the readme, so I'll add :+1:

**Comment by x-m-el** [comment]
Besides that, I used `local` instead of `locale` everywhere, will fix that too :D

**Review by elpoelma — APPROVED** [review]

**Pull request merged**
