### PR TITLE
Update `@lblod/ember-rdfa-editor` and  `@lblod/ember-rdfa-editor-lblod-plugins` packages

### PR DESCRIPTION
**Pull request by elpoelma**
## Overview
This PR includes the three following package updates:
-  `@lblod/ember-rdfa-editor` to 9.0.2
-  `@lblod/ember-rdfa-editor-lblod-plugins` to 16.0.1
-  `ember-intl` to 6.1.0 (peerdep of the editor)

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check cancel/go-back flows
- [x] Check database state correct when deleting/updating (especially regarding relationships)
- [x] changelog
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Review by abeforgit — CHANGES_REQUESTED** [review]
this breaks `ember serve` for me
```
TypeError: intl is undefined
```

**Comment by elpoelma** [comment]
> this breaks `ember serve` for me
> 
> ```
> TypeError: intl is undefined
> ```

huh weird, do you just get it in your terminal when serving the app? I don't get the same error...

**Comment by elpoelma** [comment]
> no at runtime in the browser console, but im getting it also randomly on the editor repo, don't really know what's going on

Will also try it on the editor repo and see what gives. Maybe try clearing the `node_modules` folder?

**Comment by elpoelma** [comment]
Should be fixed now by reverting back to `ember-intl` 5.7.2

**Pull request merged**
